
export const FORM_STATUS = {
    DRAFT: "DRAFT",
    SUBMITTED: "SUBMITTED",
    AUTHORISED: "AUTHORISED",
    VALIDATED: "VALIDATED",
    COMPLETED: "COMPLETED",
}

export const PERMISSIONS = {
    ADMINISTRATOR_GROUP: "ADMIN",
    MANAGER_GROUP: "MANAGER",
    SOCIAL_WORKER_GROUP: "SOCIAL_WORKER",
}